repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v0.9.1
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    # ensure JSON files are well-formed and formatted
    - id: check-json
    - id: pretty-format-json
      args: ["--autofix", "--no-sort-keys"]
- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black
      name: "Autoformat python files"
      language_version: python3.6
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.8
  hooks:
    - id: flake8
      name: "Lint python files"
      types: [python]
      language_version: python3
      additional_dependencies: ['flake8-bugbear==19.3.0']
- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21
  hooks:
    - id: isort
      name: "Sort python imports"
      types: [python]
      language_version: python3
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.720
  hooks:
    - id: mypy
      name: "Type-check python"
      types: [python]
- repo: local
  hooks:
    - id: shellcheck
      name: "Lint shell scripts"
      entry: shellcheck
      language: system
      types: [shell,bash]
