repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.0.1
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    # ensure JSON files are well-formed and formatted
    - id: check-json
    - id: pretty-format-json
      args: ["--autofix", "--no-sort-keys"]
- repo: https://github.com/psf/black
  rev: 21.9b0
  hooks:
    - id: black
      language_version: python3.6
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      types: [python]
      language_version: python3
      additional_dependencies: ['flake8-bugbear==19.3.0']
- repo: https://github.com/timothycrosley/isort
  rev: 5.9.3
  hooks:
    - id: isort
      types: [python]
      language_version: python3
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
    - id: mypy
      types: [python]
      additional_dependencies:
        - globus-sdk==3.0.2
        - types-docutils
        - types-requests
      files: ^globus_search_cli/
- repo: local
  hooks:
    - id: shellcheck
      name: "Lint shell scripts"
      entry: shellcheck
      language: system
      types: [shell,bash]
